export const companies = [
    { "img_source": "/assets/tcs.png", "href": "https://www.tcs.com/" },
    { "img_source": "/assets/google.png", "href": "https://www.google.co.in/" },
    { "img_source": "/assets/cognizant.png", "href": "https://www.cognizant.com/in/en" },
    { "img_source": "/assets/amazon.png", "href": "https://www.amazon.in/" },
    { "img_source": "/assets/wipro.png", "href": "https://www.wipro.com/en-IN/" },
    { "img_source": "/assets/capgemni.png", "href": "https://www.capgemini.com/" },
    { "img_source": "/assets/hcl.png", "href": "https://www.hcltech.com/" },
    { "img_source": "/assets/infosis.png", "href": "https://www.infosys.com/" },
    { "img_source": "/assets/kpit.png", "href": "https://www.kpit.com/" },
    { "img_source": "/assets/techmahindra.png", "href": "https://www.techmahindra.com/en-in/?f=3640242596" },
    { "img_source": "/assets/Accenture.png", "href": "https://www.accenture.com" },
    { "img_source": "/assets/godrej.png", "href": "https://www.godrej.com" },
    { "img_source": "/assets/persistent.png", "href": "https://www.persistent.com" },
    { "img_source": "/assets/trianz.png", "href": "https://www.trianz.com" },
]
