import { FacultyModel } from "../models/FacultyModel.js";

export const faculty = [
	new FacultyModel(
		"Prof. Dilip Bhattacharya",
		"Professor & Director",
		"Ph.D",
		"40 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Prof. Sripati Mukhopadhyay",
		"Professor",
		"Ph.D",
		"40 yrs",
		"#",
	),
	new FacultyModel(
		"Prof. Dilip Kumar Maity",
		"Professor & Principal",
		"Ph.D",
		"20 yrs",
		"#",
	),
	new FacultyModel("Prof. Partha Dey", "Professor", "Ph.D", "24 yrs", "#"),
	new FacultyModel(
		"Prof. Abhijit Banerjee",
		"Professor",
		"Ph.D",
		"18 yrs 9 mts",
		"#",
	),
	new FacultyModel(
		"Krishna Bhowal",
		"Associate Professor & Registrar",
		"Ph.D",
		"17 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Arindrajit Pal",
		"Associate Professor",
		"Ph.D",
		"18 yrs 7 mts",
		"#",
	),
	new FacultyModel(
		"Basab Chatterjee",
		"Associate Professor",
		"Ph.D",
		"19 yrs 1 mts",
		"#",
	),
	new FacultyModel(
		"Sirshendu Saha",
		"Associate Professor",
		"Ph.D",
		"16 yrs",
		"#",
	),
	new FacultyModel(
		"Sandip Saha Chowdhury",
		"Associate Professor",
		"Ph.D",
		"22 yrs",
		"#",
	),
	new FacultyModel(
		"Hiranmoy Mondal",
		"Associate Professor",
		"Ph.D",
		"17 yrs 2 mts",
		"#",
	),
	new FacultyModel("Srinjoy Bid", "Associate Professor", "Ph.D", "20 yrs", "#"),
	new FacultyModel(
		"Abhijit Mallick",
		"Associate Professor",
		"Ph.D",
		"21 yrs 5 mts",
		"#",
	),
	new FacultyModel(
		"Biswaranjan Das",
		"Associate Professor",
		"Ph.D",
		"18 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Baishakhi Bhattacharya",
		"Associate Professor",
		"Ph.D",
		"14 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Subhra Chatterjee",
		"Associate Professor",
		"Ph.D",
		"14 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Poulomi Deb Roy Chowdhury",
		"Associate Professor",
		"Ph.D",
		"17 yrs 6 mts",
		"#",
	),
	new FacultyModel(
		"Sourav Kayal",
		"Associate Professor",
		"Ph.D",
		"10 yrs 8 mts",
		"#",
	),
	new FacultyModel("Asish Mohan", "Associate Professor", "Ph.D", "14 yrs", "#"),
	new FacultyModel(
		"Jhumpa De",
		"Associate Professor",
		"Ph.D",
		"15 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Bappaditya Mondal",
		"Associate Professor",
		"Ph.D",
		"16 yrs",
		"#",
	),
	new FacultyModel(
		"Paulomi Chattopadhyay",
		"Associate Professor",
		"Ph.D",
		"15 yrs 6 mts",
		"#",
	),
	new FacultyModel("Subir Panja", "Associate Professor", "Ph.D", "14 yrs", "#"),
	new FacultyModel(
		"Abhinaba Dutta",
		"Associate Professor",
		"Ph.D",
		"16 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Jayati Mukherjee",
		"Assistant Professor",
		"Ph.D",
		"3 yrs",
		"#",
	),
	new FacultyModel(
		"Oendrila Samanta",
		"Assistant Professor",
		"Ph.D",
		"2 yrs",
		"#",
	),
	new FacultyModel(
		"Kanishka Majumder",
		"Assistant Professor",
		"Ph.D",
		"9 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Sukanta Bose",
		"Assistant Professor",
		"Ph.D",
		"13 yrs",
		"#",
	),
	new FacultyModel("Nabanita Das", "Assistant Professor", "Ph.D", "1 yr", "#"),
	new FacultyModel(
		"Soumya Chatterjee",
		"Assistant Professor",
		"Ph.D",
		"15 yrs 10 mts",
		"#",
	),
	new FacultyModel(
		"Ramnayan Mukherjee",
		"Assistant Professor",
		"Ph.D",
		"8 yrs",
		"#",
	),
	new FacultyModel(
		"Somnath Mukherjee",
		"Assistant Professor",
		"Ph.D",
		"8 yrs 9 mts",
		"#",
	),
	new FacultyModel(
		"Anshupriya Shome",
		"Assistant Professor",
		"Ph.D",
		"3 yrs 2 mts",
		"#",
	),
	new FacultyModel(
		"Dhrubajyoti Mondal",
		"Assistant Professor",
		"Ph.D",
		"3 yrs 3 mts",
		"#",
	),
	new FacultyModel(
		"Vikram Bhagat",
		"Assistant Professor",
		"Ph.D",
		"13 yrs",
		"#",
	),
	new FacultyModel(
		"Sreetama Sinha",
		"Assistant Professor",
		"Ph.D",
		"2 yrs",
		"#",
	),
	new FacultyModel(
		"Shalini Misra",
		"Assistant Professor",
		"Ph.D",
		"4 yrs",
		"#",
	),
	new FacultyModel(
		"Rituparna Pakhira",
		"Assistant Professor",
		"Ph.D",
		"2 yr 3 mts",
		"#",
	),
	new FacultyModel(
		"Avishek Chakraborty",
		"Assistant Professor",
		"Ph.D",
		"2 yr 3 mts",
		"#",
	),
	new FacultyModel(
		"Nisantika Biswas",
		"Assistant Professor",
		"Ph.D",
		"10 yrs 2 mts",
		"#",
	),
	new FacultyModel(
		"Sanjib Kundu",
		"Assistant Professor",
		"Ph.D",
		"12 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Partha Ghosh",
		"Assistant Professor",
		"Ph.D",
		"10 yrs",
		"#",
	),
	new FacultyModel(
		"Smarajit Maity",
		"Assistant Professor",
		"Ph.D",
		"18 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Tapas Tewary",
		"Assistant Professor",
		"Ph.D",
		"14 yrs 7 mts",
		"#",
	),
	new FacultyModel(
		"Nayan Ranjan Das",
		"Assistant Professor",
		"Ph.D",
		"2 yrs",
		"#",
	),
	new FacultyModel(
		"Soumendu Banerjee",
		"Assistant Professor",
		"Ph.D",
		"10 yrs",
		"#",
	),
	new FacultyModel(
		"Snehasish Saha",
		"Assistant Professor",
		"Ph.D",
		"6 yrs",
		"#",
	),
	new FacultyModel(
		"Debamalya Ghosh",
		"Assistant Professor",
		"Ph.D",
		"2 yrs",
		"#",
	),
	new FacultyModel(
		"Sunanda Sinha",
		"Assistant Professor",
		"Ph.D",
		"2 yrs",
		"#",
	),
	new FacultyModel(
		"Moupikta Mukherjee",
		"Assistant Professor",
		"Ph.D",
		"2 yrs",
		"#",
	),
	new FacultyModel(
		"Pinak Pani Mukherjee",
		"Assistant Professor",
		"M.Tech",
		"13 yrs 1 mts",
		"#",
	),
	new FacultyModel(
		"Niloy Ghosh",
		"Assistant Professor",
		"M.E",
		"7 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Nibedita Saha",
		"Assistant Professor",
		"M.E",
		"9 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Jayjeet Sarkar",
		"Assistant Professor",
		"M.Tech",
		"15 yrs 1 mts",
		"#",
	),
	new FacultyModel(
		"Supantha Das",
		"Assistant Professor",
		"M.E",
		"10 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Swarup Sarkar",
		"Assistant Professor",
		"M.Tech",
		"14 yrs 6 mts",
		"#",
	),
	new FacultyModel(
		"Nupur Chhaule",
		"Assistant Professor",
		"M.Tech",
		"12 yrs 7 mts",
		"#",
	),
	new FacultyModel(
		"Rakhi Neogi",
		"Assistant Professor",
		"M.Tech",
		"12 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Suman Bhattacharya",
		"Assistant Professor",
		"M.Tech",
		"14 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Kaushik Roy Chowdhury",
		"Assistant Professor",
		"M.Tech",
		"18 yrs",
		"#",
	),
	new FacultyModel(
		"Biswajit Patra",
		"Assistant Professor",
		"M.Tech",
		"3 yrs 4 mts",
		"#",
	),
	new FacultyModel(
		"Priyanka Bhattacharya",
		"Assistant Professor",
		"M.Tech",
		"7 yrs",
		"#",
	),
	new FacultyModel(
		"Chiranjit Guchait",
		"Assistant Professor",
		"M.Tech",
		"9 yrs 11 mts",
		"#",
	),
	new FacultyModel(
		"Subhasish Das",
		"Assistant Professor",
		"M.Tech",
		"1 yrs",
		"#",
	),
	new FacultyModel(
		"Prasenjit Das",
		"Assistant Professor",
		"M.Tech",
		"20 yrs",
		"#",
	),
	new FacultyModel(
		"Somen Kumar Hati",
		"Assistant Professor",
		"M.Tech",
		"19 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Jyotirmoy Panja",
		"Assistant Professor",
		"M.BA",
		"1 yr",
		"#",
	),
	new FacultyModel(
		"Sailik Sen",
		"Assistant Professor",
		"M.Tech",
		"3 yrs 1 mts",
		"#",
	),
	new FacultyModel(
		"Kaushik Bose",
		"Assistant Professor",
		"M.Tech",
		"3 yrs 2 mts",
		"#",
	),
	new FacultyModel(
		"Garima Rani",
		"Assistant Professor",
		"M.Tech",
		"4 yrs 1 mts",
		"#",
	),
	new FacultyModel(
		"Subhankar Roy",
		"Assistant Professor",
		"M.Tech",
		"11 yrs 7 mts",
		"#",
	),
	new FacultyModel(
		"K.M.Priti",
		"Assistant Professor",
		"MCA",
		"4 yrs 4 mts",
		"#",
	),
	new FacultyModel(
		"Aaheli Sarkar",
		"Assistant Professor",
		"M.Tech",
		"3 yrs",
		"#",
	),
	new FacultyModel(
		"Ashutosh Kumar",
		"Assistant Professor",
		"M.Tech",
		"3 yrs 4 mts",
		"#",
	),
	new FacultyModel(
		"Firoj Ahamad",
		"Assistant Professor",
		"M.Tech",
		"4 yrs 1 mts",
		"#",
	),
	new FacultyModel(
		"Srikrishna Awasthi",
		"Assistant Professor",
		"M.Tech",
		"4 yrs 1 mts",
		"#",
	),
	new FacultyModel(
		"Jitendra Banerjee",
		"Assistant Professor",
		"M.E",
		"13 yrs",
		"#",
	),
	new FacultyModel(
		"Suman Mukherjee",
		"Assistant Professor",
		"M.E",
		"4 yrs 1 mts",
		"#",
	),
	new FacultyModel(
		"Buddhadeb Chatterjee",
		"Assistant Professor",
		"M.E",
		"11 yrs 2 mts",
		"#",
	),
	new FacultyModel(
		"Jyotirmoy Chakrabarti",
		"Assistant Professor",
		"M.Tech",
		"14 yrs 2 mts",
		"#",
	),
	new FacultyModel("Swarna Das", "Assistant Professor", "M.E", "9yrs", "#"),
	new FacultyModel(
		"Amit Kumar Nandi",
		"Assistant Professor",
		"M.E",
		"12 yrs 7 mts",
		"#",
	),
	new FacultyModel(
		"Md. Ehtesham",
		"Assistant Professor",
		"M.Tech",
		"3 yrs",
		"#",
	),
	new FacultyModel(
		"Partha Banerjee",
		"Assistant Professor",
		"M.Tech",
		"8 yrs",
		"#",
	),
	new FacultyModel(
		"Divyangna Sharma",
		"Assistant Professor",
		"M.Tech",
		"4 yrs 1 mts",
		"#",
	),
	new FacultyModel(
		"Subham Pramanik",
		"Assistant Professor",
		"M.Tech",
		"13 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Netai Das",
		"Assistant Professor",
		"M.Tech",
		"2 yrs 2 mts",
		"#",
	),
	new FacultyModel(
		"Manisha",
		"Assistant Professor",
		"M.Tech",
		"3 yrs 4 mts",
		"#",
	),
	new FacultyModel(
		"Mintu Dey",
		"Assistant Professor",
		"M.Tech",
		"2 yrs 1 mts",
		"#",
	),
	new FacultyModel(
		"Hiralal Kumar",
		"Assistant Professor",
		"M.E",
		"2 yrs 1 mts",
		"#",
	),
	new FacultyModel(
		"Manish Sharma",
		"Assistant Professor",
		"M.Tech",
		"4 yrs",
		"#",
	),
	new FacultyModel(
		"Abhijit Patra",
		"Assistant Professor",
		"M.E",
		"14 yrs 5 mts",
		"#",
	),
	new FacultyModel(
		"Subhradeep Maitra",
		"Assistant Professor",
		"M.Tech",
		"1 yr",
		"#",
	),
	new FacultyModel(
		"Bamdeb Banerjee",
		"Assistant Professor",
		"M.Tech",
		"19 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Debasish Sur",
		"Assistant Professor",
		"M.Tech",
		"10 yrs 7 mts",
		"#",
	),
	new FacultyModel(
		"Debjani Bhattacharya",
		"Assistant Professor",
		"M.Tech",
		"13 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Kaustav Bhadar",
		"Assistant Professor",
		"M.Tech",
		"9 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Sayan Das",
		"Assistant Professor",
		"M.Tech",
		"3 yrs 2 mts",
		"#",
	),
	new FacultyModel(
		"Suman Sengupta",
		"Assistant Professor",
		"M.Tech",
		"28 yrs",
		"#",
	),
	new FacultyModel(
		"Gaurav Shalot",
		"Assistant Professor",
		"M.Tech",
		"4 yrs 1 mts",
		"#",
	),
	new FacultyModel(
		"Soumitra Das",
		"Assistant Professor",
		"M.Tech",
		"2 yrs 2 mts",
		"#",
	),
	new FacultyModel(
		"Sandipan Misra",
		"Assistant Professor",
		"M.Tech",
		"13 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Suman Kumar Das",
		"Assistant Professor",
		"M.Tech",
		"13 yrs 7 mts",
		"#",
	),
	new FacultyModel(
		"Abhijit Basu",
		"Assistant Professor",
		"M.Tech",
		"12 yrs 2 mts",
		"#",
	),
	new FacultyModel(
		"Aloke Kumar Ghoshal",
		"Assistant Professor",
		"M.B.A",
		"16 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Anindya Saha",
		"Assistant Professor",
		"M.Sc",
		"20 yrs 2 mts",
		"#",
	),
	new FacultyModel(
		"Soma Banerjee",
		"Assistant Professor",
		"MBA",
		"10 yrs 1 mts",
		"#",
	),
	new FacultyModel("Arindam Dey", "Assistant Professor", "M.Sc", "3 yrs", "#"),
	new FacultyModel(
		"Dwijen Biswas",
		"Assistant Professor",
		"MBA",
		"3 yrs 2 mts",
		"#",
	),
	new FacultyModel(
		"Shaoli Mukherjee",
		"Assistant Professor",
		"MBA",
		"3 yrs 2 mts",
		"#",
	),
	new FacultyModel(
		"Anil Kumar Sharma",
		"Assistant Professor",
		"MBA",
		"12 yrs2 mts",
		"#",
	),
	new FacultyModel(
		"Uday Kumar Mandal",
		"Assistant Professor",
		"MCA, M.Tech",
		"15 yrs 8 mts",
		"#",
	),
	new FacultyModel(
		"Venu Gopal",
		"Assistant Professor",
		"MCA",
		"4 yrs 2 mts",
		"#",
	),
	new FacultyModel(
		"Suman Goswami",
		"Assistant Professor",
		"M.Tech",
		"2 yrs 2 mts",
		"#",
	),
	new FacultyModel(
		"Sarjita Soo",
		"Assistant Professor",
		"MCA, M.Tech",
		"4 yrs",
		"#",
	),
	new FacultyModel(
		"Suchibrata Dutta",
		"Assistant Professor",
		"M.Tech",
		"14 yrs 3 mts",
		"#",
	),
	new FacultyModel(
		"Shamik Kumar Bose",
		"Assistant Professor",
		"M.Tech",
		"5 yrs",
		"#",
	),
	new FacultyModel(
		"Poulomi Ganguly",
		"Assistant Professor",
		"M.Tech",
		"10 yrs",
		"#",
	),
	new FacultyModel(
		"Dibyendu Kumar Ghosh",
		"Assistant Professor",
		"M.Tech",
		"1 yrs",
		"#",
	),
	new FacultyModel(
		"Sajal Sasmal",
		"Assistant Professor",
		"M.Tech",
		"9 yrs",
		"#",
	),
	new FacultyModel(
		"Dipanjan De",
		"Assistant Professor",
		"M.Tech",
		"15 yrs",
		"#",
	),
	new FacultyModel(
		"Shiladitya Acharyya",
		"Assistant Professor",
		"M.Tech",
		"1 yr",
		"#",
	),
	new FacultyModel(
		"Jayanta Digar",
		"Assistant Professor",
		"M.Tech",
		"2 yrs",
		"#",
	),
	new FacultyModel(
		"Anumita Singha Roy",
		"Assistant Professor",
		"M.Tech",
		"4 yrs",
		"#",
	),
	new FacultyModel(
		"Sruti Mondal",
		"Assistant Professor",
		"M.Tech",
		"2 yrs",
		"#",
	),
	new FacultyModel(
		"Tanmoy Makar",
		"Assistant Professor",
		"M.Tech",
		"2 yrs",
		"#",
	),
	new FacultyModel(
		"Arun Kumar Sadhu",
		"Assistant Professor",
		"M.Tech",
		"19 yrs",
		"#",
	),
	new FacultyModel(
		"Priya Raj Chandra",
		"Assistant Professor",
		"M.Tech",
		"1 yrs",
		"#",
	),
	new FacultyModel(
		"Dipanwita Saha",
		"Assistant Professor",
		"M..Tech",
		"1 yrs",
		"#",
	),
];
